### ISSUE TITLE
Lines 171-176 in RequestApi(self, url)

### ISSUE THREAD

**Issue by CodeBradley** [arteria/python-uptimerobot#9]
I'm extending your code to include some additional API functions and this method was returning None. The problem is that if UptimeRobot returns stat:'fail' then the method doesn't return. This is because stat does exist, but the value is not 'ok'. I believe I fixed this issue by updating the code to:

```
def requestApi(self, url):
        response = urllib_request.urlopen(url)
        content = response.read().decode('utf-8')
        jContent = json.loads(content)
        if jContent.get('stat'):
            stat = jContent.get('stat')
            if stat == "ok":
                return True, jContent
        return False, jContent
```

**Comment by ticoombs** [comment]
@CodeBradley Please submit a PR with this change as you are correct.

**Comment by walterrenner** [comment]
Thanks @CodeBradley for pointing this out.

As @ticoombs mentioned, would you please send a PR with your changes.

**Comment by CodeBradley** [comment]
I think I submitted this correctly. First time doing a pull request

**Comment by walterrenner** [comment]
@CodeBradley congratulations on your first PR and also thanks you for your contribution.

I'll release your changes in the next hours, so you can install your fix from PyPi.

**Comment by CodeBradley** [comment]
Thank you! It feels right.. I've extended the code a bit, and I will probably extend it a little more, so I'll do it again and you guys can see if you want to add it in or not.
